### ISSUE TITLE
Allow direct output from inference

### ISSUE THREAD

**Issue by fakerybakery** [sidharthrajaram/StyleTTS2#1]
Hi,
Might it be possible to allow users to make the model output a Python object instead of saving it to a file?
Thank you!

**Comment by sidharthrajaram** [comment]
The `output_wav_file` argument to `inference()` is optional. The audio will be saved to a file only if something is provided to that argument. 

`inference()` returns the numpy array of the model output (audio data) regardless. Was that what you were looking for? Or did you have a different different format/object in mind?

```
my_tts = tts.StyleTTS2()

# out is a numpy array of output audio data
out = my_tts.inference("Hello there, I am now a python package.")
```

**Comment by fakerybakery** [comment]
Perfect, thank you!
