### ISSUE TITLE
Use Tortoise splitter

### ISSUE THREAD

**Issue by fakerybakery** [sidharthrajaram/StyleTTS2#11]
Hi,
I saw your long text inference uses the LangChain splitter, have you considered using [Tortoise](https://github.com/neonbjb/tortoise-tts)'s splitter, which tries to keep sentences together?
Thanks!

**Comment by sidharthrajaram** [comment]
Did you mean [this one](https://github.com/neonbjb/tortoise-tts/blob/main/tortoise/utils/text.py#L4)? 
Yeah, this one seems to work significantly better than LangChain. Will add that to the list of updates for the next release.

**Comment by sidharthrajaram** [comment]
Switched to Tortoise-based `txtsplit` over LangChain splitter in 0d744ab. Will include in the next release.
