### ISSUE TITLE
Are there any known issues of this running on GPU instead of CPU? or at least can this run on GPU? or is there a option to make it run on GPU?

### ISSUE THREAD

**Issue by DrewThomasson** [sidharthrajaram/StyleTTS2#15]
Are there any known issues of this running on GPU instead of CPU? or at least can this run on GPU? or is there a option to make it run on GPU?

**Comment by sidharthrajaram** [comment]
The model is automatically loaded onto GPU if it's available (see [here](https://github.com/sidharthrajaram/StyleTTS2/blob/main/src/styletts2/tts.py#L77) for device selection). It can run on either GPU or CPU.
