### ISSUE TITLE
torch version specifity

### ISSUE THREAD

**Issue by rsxdalv** [sidharthrajaram/StyleTTS2#17]
https://github.com/sidharthrajaram/StyleTTS2/blob/350b8889d75a52c2c695dafa7ba4682386be0b96/pyproject.toml#L17C1-L18C1

I am looking to integrate StyleTTS2 into my repository; however the base version is currently 2.0.0. Having the version be as specific as it is here will cause torch to be reinstalled or fail to install. (Usually meaning that the CUDA version gets removed). Is the version a hard requirement for this project?

**Comment by sidharthrajaram** [comment]
Merged #18 , will include in the next release.
