### ISSUE TITLE
Return value as byte stream

### ISSUE THREAD

**Issue by ManueleNolli** [sidharthrajaram/StyleTTS2#19]
Hi, great work!

Do you think it might be possible to add a method that returns the wav as a byte stream and does not write to the file system?

I would be happy to help! 😄

**Comment by sidharthrajaram** [comment]
Hi @ManueleNolli , thanks for the note! I'm in the process of better organizing the abstractions for inference, so this would be a nice feature to also have natively as a flag or something. 

In the meanwhile, a solution that would work is passing a `BytesIO` object as the `output_wav_file` argument to `inference()` and then extracting the byte stream like this:

```
# creating a BytesIO object to use as a buffer instead of a file
buffer = io.BytesIO()

output = tts.inference(... , output_wav_file=buffer, ...)

# get byte stream
byte_stream = buffer.getvalue()
```

Alternatively, if you want to write to a file AND get the byte stream, you could call `scipy.io.wavfile.write` on the output numpy array from `inference()`:

```
output = tts.inference(...)
buffer = io.BytesIO()
scipy.io.wavfile.write(buffer, rate=output_sample_rate, data=output)
byte_stream = buffer.getvalue()
```

**Comment by ManueleNolli** [comment]
Awesome, thank you so much for the answer and the examples!
