### ISSUE TITLE
How do I use inference() method for Hindi language?

### ISSUE THREAD

**Issue by tanishbajaj101** [sidharthrajaram/StyleTTS2#24]
I am trying to use TTS for devanagari script but I'm getting an error

Traceback (most recent call last):
File "C:\StyleTTS2\tts.py", line 7, in
other_tts.inference("कैसे हो आप", output_wav_file="another_test.wav")
File "C:\StyleTTS2\virt\lib\site-packages\styletts2\tts.py", line 273, in inference
pred_aln_trg[i, c_frame:c_frame + int(pred_dur[i].data)] = 1
IndexError: invalid index of a 0-dim tensor. Use tensor.item() in Python or tensor.item<T>() in C++ to convert a 0-dim tensor to a number

I observed in other TTS like XTTS v2 there seems to be an in-built option that lets you select which languages' text we are giving it to process

Is there an ibuilt option? Do I have to use PLBERT for this in a special way i'm not aware about?

**Comment by sidharthrajaram** [comment]
This package, by default, uses the pre-trained English PL-BERT model. If you have a PL-BERT model trained on Devanagari script, then you could [pass a custom config](https://github.com/sidharthrajaram/StyleTTS2/blob/main/src/styletts2/tts.py#L73) similar to this [default config](https://github.com/sidharthrajaram/StyleTTS2/blob/main/src/styletts2/Configs/config_libritts.yml#L17).

By passing a custom config, you can override the default behavior of using the default checkpoints for any module (including PL-BERT). 

 The authors of StyleTTS2 mention this situation in their repo README: https://github.com/yl4579/StyleTTS2?tab=readme-ov-file#pre-trained-modules . They reference a [multilingual PL-BERT pretrained model](https://huggingface.co/papercup-ai/multilingual-pl-bert), but I took a look at it now and it unfortunately does not seem to be trained on Devanagari script.
