### ISSUE TITLE
issue with phoneme.py that I fixed?

### ISSUE THREAD

**Issue by DrewThomasson** [sidharthrajaram/StyleTTS2#5]
idk why but when I was trying to implement this into my voxnovel project it was running into this error when switching voice actors:

Exception in thread Thread-1 (generate_audio):
Traceback (most recent call last):
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/admin/test/VoxNovel/gui_run.py", line 1920, in generate_audio
    generate_style(fragment, audio_file_ref, f"Working_files/temp/{temp_count}.wav")
  File "/Users/admin/test/VoxNovel/gui_run.py", line 1714, in generate_style
    styleTTS.inference(text,refrence_audio, output)
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/site-packages/styletts2/tts.py", line 204, in inference
    phonemized_text = self.phoneme_converter.phonemize(text)
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/site-packages/styletts2/phoneme.py", line 14, in phonemize
    phonemized.append(''.join(word.phonemes))
TypeError: can only join an iterable:

which I then applied this fix for it:

from gruut import sentences
from collections.abc import Iterable  # Import to check if an object is iterable

class PhonemeConverter:
    def phonemize(self, text):
        pass

class GruutPhonemizer(PhonemeConverter):
    def phonemize(self, text, lang='en-us'):
        phonemized = []
        for sent in sentences(text, lang=lang):  # Use the lang parameter
            for word in sent:
                # Check if word.phonemes is an iterable before joining
                if isinstance(word.phonemes, Iterable):
                    phonemized.append(''.join(word.phonemes))
                else:
                    # Handle the non-iterable case, for example, append directly if it's a string
                    phonemized.append(word.phonemes)
        phonemized_text = ' '.join(phonemized)
        return phonemized_text

class PhonemeConverterFactory:
    @staticmethod
    def load_phoneme_converter(name: str, **kwargs):
        if name == 'gruut':
            return GruutPhonemizer()
        else:
            raise ValueError("Invalid phoneme converter.")

Which came up with this error:
Exception in thread Thread-1 (generate_audio):
Traceback (most recent call last):
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/admin/test/VoxNovel/gui_run.py", line 1920, in generate_audio
    generate_style(fragment, audio_file_ref, f"Working_files/temp/{temp_count}.wav")
  File "/Users/admin/test/VoxNovel/gui_run.py", line 1714, in generate_style
    styleTTS.inference(text,refrence_audio, output)
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/site-packages/styletts2/tts.py", line 204, in inference
    phonemized_text = self.phoneme_converter.phonemize(text)
  File "/Users/admin/anaconda3/envs/tts/lib/python3.10/site-packages/styletts2/phoneme.py", line 19, in phonemize
    phonemized_text = ' '.join(phonemized)
TypeError: sequence item 4: expected str instance, NoneType found:

which I fixed with this code and now it works fine:

from gruut import sentences
from collections.abc import Iterable  # Import to check if an object is iterable

class PhonemeConverter:
    def phonemize(self, text):
        pass

class GruutPhonemizer(PhonemeConverter):
    def phonemize(self, text, lang='en-us'):
        phonemized = []
        for sent in sentences(text, lang=lang):  # Use the lang parameter
            for word in sent:
                # Check if word.phonemes is not None and is an iterable before joining
                if word.phonemes and isinstance(word.phonemes, Iterable):
                    phonemized.append(''.join(word.phonemes))
                elif word.phonemes:
                    # Handle the non-iterable but not None case, e.g., append directly if it's a string
                    phonemized.append(word.phonemes)
                # Ignore if word.phonemes is None
        phonemized_text = ' '.join(phonemized)
        return phonemized_text

class PhonemeConverterFactory:
    @staticmethod
    def load_phoneme_converter(name: str, **kwargs):
        if name == 'gruut':
            return GruutPhonemizer()
        else:
            raise ValueError("Invalid phoneme converter.")

In this updated version:

The code checks if word.phonemes is not None and is an iterable before attempting to join it.
If word.phonemes is not None but not an iterable, it appends it directly (assuming it's a string).
If word.phonemes is None, it ignores that word and does not append anything to phonemized.

**Comment by DrewThomasson** [comment]
working code is this for clarification:

from gruut import sentences
from collections.abc import Iterable  # Import to check if an object is iterable

class PhonemeConverter:
    def phonemize(self, text):
        pass

class GruutPhonemizer(PhonemeConverter):
    def phonemize(self, text, lang='en-us'):
        phonemized = []
        for sent in sentences(text, lang=lang):  # Use the lang parameter
            for word in sent:
                # Check if word.phonemes is not None and is an iterable before joining
                if word.phonemes and isinstance(word.phonemes, Iterable):
                    phonemized.append(''.join(word.phonemes))
                elif word.phonemes:
                    # Handle the non-iterable but not None case, e.g., append directly if it's a string
                    phonemized.append(word.phonemes)
                # Ignore if word.phonemes is None
        phonemized_text = ' '.join(phonemized)
        return phonemized_text

class PhonemeConverterFactory:
    @staticmethod
    def load_phoneme_converter(name: str, **kwargs):
        if name == 'gruut':
            return GruutPhonemizer()
        else:
            raise ValueError("Invalid phoneme converter.")

**Comment by DrewThomasson** [comment]
Not sure if this is helpful at all but because it fixed my issue I just wanted to share this fix with the phoneme.py file if you wanted to implement this into your repo lol

**Comment by sidharthrajaram** [comment]
Hey @DrewThomasson, yep! Pushed now. This was another thing I was meaning to address, thanks for pointing it out here. This is a great fix. 💯 

I'm almost done with long-form speech support for the next release (v0.1.6), so this change will also be included in that as well.

**Comment by sidharthrajaram** [comment]
The fix is part of the v0.1.6 release! Closing the issue now.
