### ISSUE TITLE
option to save models to local folder

### ISSUE THREAD

**Issue by mrciolino** [sidharthrajaram/StyleTTS2#7]
would like to add option to save/load from local directory.

**Comment by sidharthrajaram** [comment]
The option to load model checkpoints can be used like this:

```python
# Specific paths to a checkpoint and config can also be provided.
other_tts = tts.StyleTTS2(model_checkpoint_path='/PATH/TO/epochs_2nd_00020.pth', config_path='/PATH/TO/config.yml')
```

Saving checkpoints, however, is slightly out of scope since this package only covers inference (at least in the present form).

**Comment by mrciolino** [comment]
Was able save all files downloaded with cached_path to a local folder using a [cached_path](https://github.com/allenai/cached_path) method:

```
from cached_path import cached_path, set_cache_dir
set_cache_dir("models/")
```

the folder models/ looks like this for each file downloaded:
* 8a88800f2fe57fb..longfilename
* 8a88800f2fe57fb..longfilename.json
* 8a88800f2fe57fb..longfilename.lock

Allows you to turn off internet and still be able to run the models.
