### ISSUE TITLE
DeepPhonemizer

### ISSUE THREAD

**Issue by fakerybakery** [sidharthrajaram/StyleTTS2#9]
Hi,
I saw in your TODO you mentioned:

>  Support for DeepPhonemizer in phoneme.py

FYI I did some experiments w/ DeepPhonemizer a while back, the quality is much worse than gruut - just wanted to let you know.
Thanks for making this amazing package - super useful!

**Comment by sidharthrajaram** [comment]
Hey @fakerybakery , yeah, it looks like Gruut is still the best among the MIT/Apache-2.0 licensed crowd. Thanks for the note!
